---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	pillar_manager(pillar_manager)
	question_engine(question_engine)
	audio_pipeline(audio_pipeline<hr/><small><em>__interrupt = before</em></small>)
	answer_analyzer(answer_analyzer)
	decision_router(decision_router)
	__end__([<p>__end__</p>]):::last
	__start__ --> pillar_manager;
	answer_analyzer --> decision_router;
	audio_pipeline --> answer_analyzer;
	question_engine --> audio_pipeline;
	pillar_manager -.-> question_engine;
	pillar_manager -.-> audio_pipeline;
	pillar_manager -.-> answer_analyzer;
	pillar_manager -.-> decision_router;
	pillar_manager -.-> __end__;
	decision_router -.-> pillar_manager;
	decision_router -.-> question_engine;
	decision_router -. &nbsp;end&nbsp; .-> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
