---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	jd_parser(jd_parser)
	skill_extractor(skill_extractor)
	competency_mapper(competency_mapper)
	classifier(classifier)
	__end__([<p>__end__</p>]):::last
	__start__ --> jd_parser;
	classifier --> __end__;
	competency_mapper --> classifier;
	jd_parser --> skill_extractor;
	skill_extractor --> competency_mapper;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
