---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	router(router)
	jd_intelligence(jd_intelligence)
	resume_intelligence(resume_intelligence)
	focus_area(focus_area)
	interview(interview)
	evaluation(evaluation)
	reporting(reporting)
	complete(complete)
	error_handler(error_handler)
	__end__([<p>__end__</p>]):::last
	__start__ --> router;
	complete --> __end__;
	error_handler --> __end__;
	evaluation --> __end__;
	focus_area --> __end__;
	interview --> __end__;
	jd_intelligence --> __end__;
	reporting --> __end__;
	resume_intelligence --> __end__;
	router -.-> jd_intelligence;
	router -.-> resume_intelligence;
	router -.-> focus_area;
	router -.-> interview;
	router -.-> evaluation;
	router -.-> reporting;
	router -.-> complete;
	router -. &nbsp;error&nbsp; .-> error_handler;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
