"""verify tables

Revision ID: 3de2e48f4a49
Revises: 
Create Date: 2026-02-05 23:26:49.557285
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3de2e48f4a49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('session_id', sa.String(length=64), nullable=True))
    op.add_column('candidates', sa.Column('session_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidates', sa.Column('session_created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_candidates_session_id'), 'candidates', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_session_id'), table_name='candidates')
    op.drop_column('candidates', 'session_created_at')
    op.drop_column('candidates', 'session_expires_at')
    op.drop_column('candidates', 'session_id')
    # ### end Alembic commands ###
